BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[FAQ] (
    [id] NVARCHAR(1000) NOT NULL,
    [question] TEXT NOT NULL,
    [answer] TEXT NOT NULL,
    [order] INT NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [FAQ_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2 NOT NULL,
    CONSTRAINT [FAQ_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
